// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revoke_refresh_token.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW(),
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, userID)
	return err
}
